[project]
name = "octdata4python"
version = "0.1.0"
dependencies = [
    "auditwheel>=6.4.0",
    "build>=1.2.2.post1",
    "numpy<=1.26.0"
]

[tool.scikit-build]
sdist.exclude = [".venv/*"]
wheel.packages = ["octdata4python"]

[build-system]
requires = [
    "scikit-build-core>=0.11.3"
]
build-backend = "scikit_build_core.build"
