name: Docker Compose CI

on:
  workflow_dispatch:

jobs:
  compose-job:
    runs-on: ubuntu-24.04

    steps:
      - name: 🛸 Checkout code
        uses: actions/checkout@v4

      - name: 🚀 Set up Docker Buildx (optional, but helpful)
        uses: docker/setup-buildx-action@v3

      - name: 🐳 Set up Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: 📥 Copy wheels to host
        run: |
          docker cp octdata4python:/home/appuser/oct/octdata4python/wheelhouse .

      - name: 🧹 Tear down containers
        run: docker-compose down
